// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xocogvizxiidkdmxaeyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvY29ndml6eGlpZGtkbXhhZXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTg1MTMsImV4cCI6MjA3MzE5NDUxM30.1-PzZ4-YqiF23QSPvfXjR2TcMwtLINMEHJkw9Nda37w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});